#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

INSTALLDIR=/opt/freebox_ddns
PROG=$INSTALLDIR/.venv/bin/freebox-ddns
CONFIG=$INSTALLDIR/config.yaml

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" "$CONFIG"
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}
